# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    #nodejs: 22
  jobs:
    post_checkout:
      # Needed for some plugins/extensions to work
      - git fetch --unshallow || true
    create_environment:
      - pipenv install
    build:
      html:
      - FF_GENERATE_SOCIAL_CARDS=true pipenv run build-staging -d "$READTHEDOCS_OUTPUT/html/"
  apt_packages:
    - libcairo2-dev
    - libfreetype6-dev
    - libffi-dev
    - libjpeg-dev
    - libpng-dev
    - libz-dev
    - pngquant
    - pipenv
